import { useState } from 'react';
import { Bot, Sparkles, X } from 'lucide-react';
import { api } from '../api/client';
import type { AiRequest, AiResultDto, AiTask } from '../api/types';
import { Badge, Button, Callout, Markdown } from './ui';
import { dateTime } from '../lib/format';
import { toast } from '../app/toast';

export const AI_TASK_LABEL: Record<AiTask, string> = {
  'executive-briefing': 'Executive briefing',
  'need-analysis': 'Analyse this need',
  'opportunity-draft': 'Draft opportunity',
  'solution-discovery': 'Discover solutions',
  'submission-summary': 'Summarise submission',
  'impact-summary': 'Summarise impact',
};

export async function runAi(task: AiTask, body: AiRequest = {}): Promise<AiResultDto | null> {
  try {
    return await api.post<AiResultDto>(`/ai/${task}`, body);
  } catch (e) {
    toast.error((e as Error).message);
    return null;
  }
}

/** Renders one CIVIC AI result with its mode, citations and the human-decides disclaimer (AI-G1/G2). */
export function AiResult({ result }: { result: AiResultDto }) {
  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-2">
        <Badge tone="gold"><Sparkles size={11} /> CIVIC AI draft</Badge>
        <Badge tone={result.mode === 'GEMINI' ? 'brand' : 'neutral'} title={result.mode === 'GEMINI' ? 'Generated by Gemini from platform records' : 'Template engine over platform records (no API key configured)'}>
          {result.mode === 'GEMINI' ? 'Gemini' : 'Deterministic mode'}
        </Badge>
        <span className="text-[11px] text-slate-400">{dateTime(result.generatedAt)}</span>
      </div>
      <Markdown text={result.content} />
      {result.citations.length > 0 && (
        <div>
          <div className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-slate-400">Records used</div>
          <div className="flex flex-wrap gap-1.5">
            {result.citations.map((c, i) => (
              <Badge key={i} tone="neutral" title={`${c.type} ${c.id}`}>{c.reference}{c.label && c.label !== c.reference ? ` · ${c.label}` : ''}</Badge>
            ))}
          </div>
        </div>
      )}
      <Callout tone="warning">{result.disclaimer}</Callout>
    </div>
  );
}

/** Inline "Ask CIVIC AI" button + result area, used on detail pages. */
export function AiInline({ task, body, label }: { task: AiTask; body?: AiRequest; label?: string }) {
  const [result, setResult] = useState<AiResultDto | null>(null);
  const [loading, setLoading] = useState(false);
  return (
    <div className="space-y-3">
      <Button variant="secondary" size="sm" icon={<Sparkles size={14} className="text-gold-500" />} loading={loading}
        onClick={async () => { setLoading(true); setResult(await runAi(task, body)); setLoading(false); }}>
        {label ?? AI_TASK_LABEL[task]}
      </Button>
      {result && (
        <div className="relative rounded-xl border border-gold-100 bg-gold-50/40 p-4">
          <button className="absolute right-2 top-2 text-slate-400 hover:text-slate-600" onClick={() => setResult(null)} aria-label="Close AI result"><X size={14} /></button>
          <AiResult result={result} />
        </div>
      )}
    </div>
  );
}

/** Slide-over drawer opened from the header. */
export function AiDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [result, setResult] = useState<AiResultDto | null>(null);
  const [loading, setLoading] = useState(false);
  if (!open) return null;
  const go = async (task: AiTask) => {
    setLoading(true);
    setResult(await runAi(task));
    setLoading(false);
  };
  return (
    <div className="animate-fade-in fixed inset-0 z-50 flex justify-end bg-slate-900/30" onMouseDown={onClose}>
      <aside onMouseDown={(e) => e.stopPropagation()} className="animate-slide-left flex h-full w-full max-w-md flex-col bg-white shadow-2xl" aria-label="CIVIC AI">
        <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
          <div className="flex items-center gap-2">
            <div className="rounded-lg bg-gold-50 p-1.5 text-gold-600"><Bot size={18} /></div>
            <div>
              <div className="text-sm font-semibold">CIVIC AI</div>
              <div className="text-[11px] text-slate-500">Grounded in platform records · AI assists, humans decide</div>
            </div>
          </div>
          <button onClick={onClose} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100" aria-label="Close"><X size={18} /></button>
        </div>
        <div className="flex flex-wrap gap-2 border-b border-slate-100 px-5 py-3">
          <Button size="sm" onClick={() => go('executive-briefing')} loading={loading}>Executive briefing</Button>
          <Button size="sm" variant="secondary" onClick={() => go('impact-summary')} disabled={loading}>Impact summary</Button>
        </div>
        <div className="flex-1 overflow-y-auto px-5 py-4">
          {result ? <AiResult result={result} /> : (
            <p className="text-sm text-slate-500">
              Ask for a briefing across needs, approvals, evaluations, implementations and impact. For need-, opportunity- or
              submission-specific help, use the CIVIC AI buttons on those pages.
            </p>
          )}
        </div>
      </aside>
    </div>
  );
}
