package com.civicflow.domain.enums;

public enum NeedCategory {
    WASTE_ENVIRONMENT, COMMUNITY_SAFETY, DIGITAL_SERVICES, LOCAL_ECONOMIC_DEVELOPMENT, INFRASTRUCTURE, WATER_ENERGY, ICT_OPERATIONS, COMMUNITY_FACILITIES
}
