package com.civicflow.domain.enums;

public enum UserRole {
    DEPARTMENT_OFFICER, DEPARTMENT_MANAGER, FINANCE_DIRECTOR, PROCUREMENT_OFFICER, EVALUATOR, PROVIDER, EXECUTIVE, AUDITOR, ADMIN, SYSTEM
}
